### ISSUE TITLE
Description of mapping file would be useful in the readme

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/lsa_for_genomes#2]
The optional -a command includes a mapping file that would be useful to be described in the README.

Also, the example command ```./lsa.rb -m `which mmseqs` -i test_files/*.faa.gz -o output``` doesn't include the mapping file, but your output directory includes metadata categories, which is not intuitive.

Of course, you could just include the test data mapping file in the README as an example.

**Comment by mooreryan** [comment]
Sort of fixed in https://github.com/mooreryan/lsa_for_genomes/releases/tag/v0.11.6
