### ISSUE TITLE
Singleton cannot be 0

### ISSUE THREAD

**Issue by seanmcallister** [mooreryan/lsa_for_genomes#6]
The option to limit the influence of singletons (-s) cannot be zero. It exits with:

```
D, [2017-10-16T18:08:54.900664 #1560] DEBUG -- : Running: Rscript 04_smalltest/metadata_groups/original/r/term_doc_dists_kmeans.doc_0_B04_faa.r
Error: object 'nan' not found
Execution halted
F, [2017-10-16T18:08:55.102034 #1560] FATAL -- : Command failed with status 'pid 1775 exit 1' when running '["Rscript 04_smalltest/metadata_groups/original/r/term_doc_dists_kmeans.doc_0_B04_faa.r"]', 'nil'
```

**Comment by seanmcallister** [comment]
Actually ran with -s 0.000001 and it also didn't work.

It did work when set to -s 0.001.

**Comment by mooreryan** [comment]
When the singletons have zero weight, you get vectors with zero length and a divide by zero error. It will now raise a better error message. The temporary fix for this is to only let singleton weight go down to `0.01` (2d6b17a2232bafcbe02b666eb141e58f81601e59).
